# Generated by Django 3.2.4 on 2021-07-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('CG', 'choose your gender'), ('0', 'Male'), ('1', 'Female')], default='CG', max_length=3, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pregnancy', models.IntegerField(null=True)),
                ('glucose', models.IntegerField(null=True)),
                ('blood_pressure', models.IntegerField(null=True)),
                ('skin_thickness', models.IntegerField(null=True)),
                ('insulin', models.IntegerField(null=True)),
                ('bmi', models.IntegerField(null=True)),
                ('pedigree', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('predicted_result', models.BooleanField(default=False)),
            ],
        ),
    ]
